language: r
warnings_are_errors: true

sudo: required

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual"
    - _R_CHECK_FORCE_SUGGESTS_=FALSE

before_install:
  - curl -OL http://raw.github.com/eddelbuettel/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - sudo add-apt-repository -y ppa:edd/misc
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - ./travis-tool.sh install_aptget r-cran-rcpp g++-4.9
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 50
  - Rscript -e "install.packages(c('devtools', 'RcppParallel', 'testthat', 'data.table', 'rmarkdown', 'knitr', 'iterators', 'glmnet', 'foreach'), repos='http://cran.us.r-project.org')"
